# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#   testing jenkin ci    https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
    desc "Submit a new Beta Build to Firebase app distribution"
    lane :beta do
        # build the release variant
        increment_version_code(app_folder_name: './app')
        gradle(task: 'clean', project_dir: '.')
        gradle(task: 'assemble', build_type: 'Debug', project_dir: '.')        
        #build_android_app(task: "assembleDebug")

        # changelog from a txt file is passed as the release note
        #changelog = File.read("../changelog.txt")

        # submit build to firebase app distribution
        firebase_app_distribution(
            app: "1:124866071882:android:d52779924b7edcf48b05b3",
            testers: "ashwinkumar202@gmail.com, ashwin7227.ak@gmail.com",
            #release_notes: changelog,
            groups: "qa-team, dev-team"
            #firebase_cli_path: "/absolute/path/to/firebase/cli/binary"
        )

        # send slack success notification after distribution completes
        slack(
          slack_url: "https://hooks.slack.com/services/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",
          message: "New build is available for testing",
          success: true,
          default_payloads: [:git_branch, :last_git_commit_message]
        )
    end
    
    # handle exception
    error do |lane, exception, options|
        # send slack failure notification
        slack(
            message: "Build failed with exception: #{exception}",
            slack_url: "https://hooks.slack.com/services/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",
            success: false,
            default_payloads: [:git_branch, :last_git_commit_message]
        )
    end
end